import type { Service, ServicePackage, HeroSlide } from '../types'

export const INITIAL_HERO_SLIDES: HeroSlide[] = [
  {
    id: 'hero-slide-1',
    subtitle: 'PATIZAN RECORDS',
    title: 'YOUR SOUND.\nYOUR SPACE.',
    description: 'A professional recording environment built for artists, producers and creators in South Florida.',
    background_image: '',
    image_position: 'center',
    primary_button_text: 'BOOK A SESSION',
    primary_button_link: '/book-session',
    secondary_button_text: 'EXPLORE THE STUDIO',
    secondary_button_link: '/studio',
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hero-slide-2',
    subtitle: 'RECORDING • PRODUCTION • MIXING',
    title: 'TURN YOUR IDEAS\nINTO SOUND.',
    description: 'From the first take to the final master, create music in a professional studio designed around your sound.',
    background_image: '',
    image_position: 'center',
    primary_button_text: 'BOOK A SESSION',
    primary_button_link: '/book-session',
    secondary_button_text: 'OUR SERVICES',
    secondary_button_link: '/services',
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hero-slide-3',
    subtitle: 'MUSIC PRODUCTION',
    title: 'MAKE SOMETHING\nPEOPLE REMEMBER.',
    description: 'Professional recording, beat production, mixing and mastering for artists ready to elevate their sound.',
    background_image: '',
    image_position: 'center',
    primary_button_text: 'BOOK A SESSION',
    primary_button_link: '/book-session',
    secondary_button_text: 'EXPLORE MUSIC',
    secondary_button_link: '/music',
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hero-slide-4',
    subtitle: 'PODCAST • VOICE • CONTENT',
    title: 'YOUR VOICE\nDESERVES A STUDIO.',
    description: 'Professional recording for podcasts, voiceovers, commercials and digital content.',
    background_image: '',
    image_position: 'center',
    primary_button_text: 'BOOK A SESSION',
    primary_button_link: '/book-session',
    secondary_button_text: 'VIEW SERVICES',
    secondary_button_link: '/services',
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hero-slide-5',
    subtitle: 'SOUTH FLORIDA RECORDING STUDIO',
    title: 'WHERE SOUND\nBECOMES CULTURE.',
    description: 'A creative studio in Tamarac, Florida built for artists, producers and creators.',
    background_image: '',
    image_position: 'center',
    primary_button_text: 'BOOK A SESSION',
    primary_button_link: '/book-session',
    secondary_button_text: 'VISIT THE STUDIO',
    secondary_button_link: '/studio',
    is_active: true,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const INITIAL_SERVICES: Service[] = [
  {
    id: 's-1',
    name: 'Recording',
    slug: 'recording',
    short_description: 'Professional vocal and instrument recording sessions with industry-standard signal chain.',
    description: 'State-of-the-art recording environment designed for artists, bands, and solo performers. Achieve the perfect take with our professional-grade microphones, acoustic treatment, and experienced engineers.',
    image_url: null,
    starting_price: 40,
    is_featured: true,
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-2',
    name: 'Podcast',
    slug: 'podcast',
    short_description: 'Professional podcast recording and production with broadcast microphones.',
    description: 'Launch or elevate your podcast with crystal-clear audio quality. Dedicated multi-track podcast desk setup with acoustic isolation.',
    image_url: null,
    starting_price: 40,
    is_featured: false,
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-3',
    name: 'Voice Over',
    slug: 'voice-over',
    short_description: 'Crystal-clear voice over recordings for commercials, audiobooks, and media.',
    description: 'From commercial spots to audiobooks and dubbing, our voice over sessions deliver pristine, broadcast-ready vocal clarity.',
    image_url: null,
    starting_price: 40,
    is_featured: false,
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-4',
    name: 'Mixing & Mastering',
    slug: 'mixing-mastering',
    short_description: 'Transform rough recordings into radio-ready, commercially competitive masters.',
    description: 'Our engineers bring analog warmth and digital surgical precision to every track. Full stem mixing, stereo balance, and streaming-compliant loudness mastering.',
    image_url: null,
    starting_price: 75,
    is_featured: false,
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-5',
    name: 'Beat Production',
    slug: 'beat-production',
    short_description: 'Custom, exclusive beat production by in-house producers across all genres.',
    description: 'Commission original, industry-ready beats tailored to your unique sound. We cover Drill, Afro, Compas, Amapiano, Hip-Hop, and Trap.',
    image_url: null,
    starting_price: 50,
    is_featured: false,
    is_active: true,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-6',
    name: 'Streaming',
    slug: 'streaming',
    short_description: 'Live streaming setup and multi-camera broadcast production.',
    description: 'Professional live streaming for concerts, creator events, and live DJ sets with studio-grade audio routing.',
    image_url: null,
    starting_price: 75,
    is_featured: false,
    is_active: true,
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-7',
    name: 'Jingle',
    slug: 'jingle',
    short_description: 'Custom sonic branding and jingles for businesses and advertising.',
    description: 'Create memorable sonic signatures and brand anthems that stick in your audience’s mind.',
    image_url: null,
    starting_price: 100,
    is_featured: false,
    is_active: true,
    display_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-8',
    name: 'DJ Tag',
    slug: 'dj-tag',
    short_description: 'Custom vocal DJ tags and drops for producers and DJs.',
    description: 'Custom signature voice tags, drops, and sweeps processed with vocal FX.',
    image_url: null,
    starting_price: 25,
    is_featured: false,
    is_active: true,
    display_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-9',
    name: 'Commercial Spot Production',
    slug: 'commercial-spot',
    short_description: 'Full commercial audio production for radio, television, and social ads.',
    description: 'End-to-end commercial audio production from voice casting and sound design to final loudness delivery.',
    image_url: null,
    starting_price: 150,
    is_featured: false,
    is_active: true,
    display_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const INITIAL_PACKAGES: ServicePackage[] = [
  {
    id: 'p-1',
    service_id: 's-1',
    name: 'Basic — 1 Hour',
    duration_hours: 1,
    price: 40,
    description: 'Quick recording sessions for singles, vocals or demos. Studio time included.',
    engineer_included: false,
    is_featured: false,
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-2',
    service_id: 's-1',
    name: 'Standard — 2 Hours',
    duration_hours: 2,
    price: 75,
    description: 'For multiple takes, vocal doubling and layering. Studio time included.',
    engineer_included: false,
    is_featured: false,
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-3',
    service_id: 's-1',
    name: 'Half Day — 4 Hours',
    duration_hours: 4,
    price: 140,
    description: 'For serious recording, EP development and extended sessions. Includes dedicated engineer.',
    engineer_included: true,
    is_featured: false,
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-4',
    service_id: 's-1',
    name: 'Full Session — 8 Hours',
    duration_hours: 8,
    price: 300,
    description: 'Complete studio lockout for album tracking and major projects. Full engineer support included.',
    engineer_included: true,
    is_featured: true,
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
